# Generated by Django 2.2.17 on 2020-11-08 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_old', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AhoyEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_id', models.IntegerField(blank=True, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=1024, null=True)),
                ('properties', models.TextField(blank=True, null=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ahoy_events',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('danish', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('english', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CategoriesEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'categories_events',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CategoriesEventSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'categories_event_series',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('hidden', models.BooleanField(blank=True, null=True)),
                ('event_id', models.IntegerField(blank=True, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'comments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('price', models.CharField(blank=True, max_length=255, null=True)),
                ('cancelled', models.BooleanField(blank=True, null=True)),
                ('long_description', models.TextField(blank=True, null=True)),
                ('comments_enabled', models.BooleanField(blank=True, null=True)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('picture_file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('picture_content_type', models.CharField(blank=True, max_length=255, null=True)),
                ('picture_file_size', models.IntegerField(blank=True, null=True)),
                ('picture_updated_at', models.DateTimeField(blank=True, null=True)),
                ('event_series_id', models.IntegerField(blank=True, null=True)),
                ('featured', models.BooleanField(blank=True, null=True)),
                ('published', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'events',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EventSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1024, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.CharField(blank=True, max_length=1024, null=True)),
                ('cancelled', models.BooleanField(blank=True, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('location_id', models.IntegerField(blank=True, null=True)),
                ('comments_enabled', models.BooleanField(blank=True, null=True)),
                ('link', models.CharField(blank=True, max_length=1024, null=True)),
                ('picture_file_name', models.CharField(blank=True, max_length=1024, null=True)),
                ('picture_content_type', models.CharField(blank=True, max_length=1024, null=True)),
                ('picture_file_size', models.IntegerField(blank=True, null=True)),
                ('picture_updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('rule', models.CharField(blank=True, max_length=1024, null=True)),
                ('days', models.CharField(blank=True, max_length=1024, null=True)),
                ('expiry', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('published', models.BooleanField(blank=True, null=True)),
                ('expiring_warning_sent', models.BooleanField(blank=True, null=True)),
                ('expired_warning_sent', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'event_series',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EventSeriesCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'event_series_categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('street_address', models.CharField(blank=True, max_length=255, null=True)),
                ('postcode', models.CharField(blank=True, max_length=255, null=True)),
                ('town', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('link', models.CharField(blank=True, max_length=1024, null=True)),
            ],
            options={
                'db_table': 'locations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1024, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('featured', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'posts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SimpleCaptchaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=40, null=True)),
                ('value', models.CharField(blank=True, max_length=6, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'simple_captcha_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255, unique=True)),
                ('encrypted_password', models.CharField(max_length=255)),
                ('reset_password_token', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('reset_password_sent_at', models.DateTimeField(blank=True, null=True)),
                ('remember_created_at', models.DateTimeField(blank=True, null=True)),
                ('sign_in_count', models.IntegerField()),
                ('current_sign_in_at', models.DateTimeField(blank=True, null=True)),
                ('last_sign_in_at', models.DateTimeField(blank=True, null=True)),
                ('current_sign_in_ip', models.CharField(blank=True, max_length=255, null=True)),
                ('last_sign_in_ip', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('confirmation_token', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmation_sent_at', models.DateTimeField(blank=True, null=True)),
                ('unconfirmed_email', models.CharField(blank=True, max_length=255, null=True)),
                ('is_admin', models.BooleanField(blank=True, null=True)),
                ('is_anonymous', models.BooleanField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Visits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_token', models.CharField(blank=True, max_length=1024, null=True, unique=True)),
                ('visitor_token', models.CharField(blank=True, max_length=1024, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('referrer', models.TextField(blank=True, null=True)),
                ('landing_page', models.TextField(blank=True, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('referring_domain', models.CharField(blank=True, max_length=1024, null=True)),
                ('search_keyword', models.CharField(blank=True, max_length=1024, null=True)),
                ('browser', models.CharField(blank=True, max_length=1024, null=True)),
                ('os', models.CharField(blank=True, max_length=1024, null=True)),
                ('device_type', models.CharField(blank=True, max_length=1024, null=True)),
                ('utm_source', models.CharField(blank=True, max_length=1024, null=True)),
                ('utm_medium', models.CharField(blank=True, max_length=1024, null=True)),
                ('utm_term', models.CharField(blank=True, max_length=1024, null=True)),
                ('utm_content', models.CharField(blank=True, max_length=1024, null=True)),
                ('utm_campaign', models.CharField(blank=True, max_length=1024, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'visits',
                'managed': False,
            },
        ),
    ]
