# Generated by Django 2.2.17 on 2020-11-08 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_group_user_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True, help_text="Enter details, which will be displayed on the group's own page. You can use Markdown.", verbose_name='description'),
        ),
    ]
