# Generated by Django 2.1.8 on 2019-11-03 15:31
import uuid

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_group_is_restricted'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
