# Generated by Django 2.1.8 on 2019-11-03 17:56
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_token_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token_expiry',
            field=models.DateTimeField(null=True),
        ),
    ]
