# Generated by Django 2.1.8 on 2019-11-03 18:23
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_token_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token_passphrase',
            field=models.CharField(help_text='One time passphrase', max_length=128, null=True),
        ),
    ]
