# Generated by Django 3.2 on 2021-09-13 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210801_0038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ('name',), 'verbose_name': 'Group'},
        ),
        migrations.AddField(
            model_name='group',
            name='deactivated',
            field=models.BooleanField(default=False, help_text='Do not show this group'),
        ),
    ]
