# Generated by Django 3.2 on 2021-10-27 22:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def migrate_locations(apps, schema_editor):
    Location = apps.get_model('users', 'Location')
    Group = apps.get_model('users', 'Group')

    for group in Group.objects.all():
        print(f"Migrating {group.name}")
        location = Location(group_ptr_id=group.pk)
        location.__dict__.update(group.__dict__)
        location.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_group_deactivated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.group')),
            ],
            options={
                'verbose_name': 'Location',
                'ordering': ('name',),
            },
            bases=('users.group',),
        ),
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='dukop_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='nick',
            field=models.CharField(blank=True, help_text='This name is displayed at events that you host or to other members of groups that you are in.', max_length=60, null=True, verbose_name='Nickname'),
        ),
        migrations.RunPython(migrate_locations, reverse_code=lambda *_: None),
    ]
