# Generated by Django 3.2 on 2021-11-01 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True, help_text="Enter details, which will be displayed on the group's own page.", verbose_name='description'),
        ),
    ]
