# Generated by Django 3.2 on 2021-04-24 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsstory',
            options={'ordering': ('-created',), 'verbose_name': 'News story', 'verbose_name_plural': 'News stories'},
        ),
    ]
