# Generated by Django 3.2 on 2021-04-25 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_newsstory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsstory',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
