# Generated by Django 2.1.14 on 2020-02-18 22:43
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0007_end_null'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, null=True)),
                ('priority', models.PositiveSmallIntegerField(default=0, help_text='0=first, 1=second etc.')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='eventupdate',
            options={'ordering': ('created',), 'verbose_name': 'Event update'},
        ),
        migrations.RemoveField(
            model_name='event',
            name='link1',
        ),
        migrations.RemoveField(
            model_name='event',
            name='link2',
        ),
        migrations.RemoveField(
            model_name='event',
            name='link3',
        ),
        migrations.RemoveField(
            model_name='event',
            name='link4',
        ),
        migrations.RemoveField(
            model_name='event',
            name='link5',
        ),
        migrations.AddField(
            model_name='eventlink',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='calendar.Event'),
        ),
    ]
