# Generated by Django 2.2.17 on 2021-01-09 23:18

from django.db import migrations, models
import django.db.models.deletion
import dukop.apps.calendar.models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0009_event_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='interval_exception',
            field=models.BooleanField(default=False, help_text='If true, changes to other events in the interval should not effect this event, as it is marked as an exception', verbose_name='exception'),
        ),
        migrations.AddField(
            model_name='eventupdate',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='calendar.Event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interval',
            name='biweekly_even',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interval',
            name='biweekly_odd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interval',
            name='ends',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interval',
            name='starts',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='interval',
            field=models.ForeignKey(blank=True, help_text='Repeats the event at some interval', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='calendar.Interval'),
        ),
        migrations.AlterField(
            model_name='eventimage',
            name='image',
            field=models.ImageField(help_text='Allowed formats: JPEG, PNG, GIF. Please upload high resolution (>1000 pixels wide).', upload_to=dukop.apps.calendar.models.image_upload_to, verbose_name='image'),
        ),
    ]
