# Generated by Django 2.2.17 on 2021-01-10 18:05

from django.db import migrations, models
import django.db.models.deletion
import dukop.apps.calendar.models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0009_event_short_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventInterval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('every_week', models.BooleanField(default=False)),
                ('biweekly_even', models.BooleanField(default=False)),
                ('biweekly_odd', models.BooleanField(default=False)),
                ('first_week_of_month', models.BooleanField(default=False)),
                ('second_week_of_month', models.BooleanField(default=False)),
                ('third_week_of_month', models.BooleanField(default=False)),
                ('last_week_of_month', models.BooleanField(default=False)),
                ('starts', models.DateTimeField(blank=True, null=True)),
                ('ends', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='interval',
        ),
        migrations.AddField(
            model_name='eventtime',
            name='interval_auto',
            field=models.BooleanField(default=False, help_text='If true, this interval is currently maintained automatically and has not been rescheduled. If the interval is edited, it may be changed automatically', verbose_name='automatic recurrence'),
        ),
        migrations.AddField(
            model_name='eventtime',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventupdate',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='calendar.Event'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventimage',
            name='image',
            field=models.ImageField(help_text='Allowed formats: JPEG, PNG, GIF. Please upload high resolution (>1000 pixels wide).', upload_to=dukop.apps.calendar.models.image_upload_to, verbose_name='image'),
        ),
        migrations.DeleteModel(
            name='Interval',
        ),
        migrations.AddField(
            model_name='eventinterval',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervals', to='calendar.Event'),
        ),
        migrations.AddField(
            model_name='eventinterval',
            name='weekday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendar.Weekday'),
        ),
    ]
