# Generated by Django 2.2.17 on 2021-04-10 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0012_spheres'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldEventSync',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_fk', models.PositiveIntegerField()),
                ('is_series', models.BooleanField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendar.Event')),
            ],
            options={
                'unique_together': {('old_fk', 'is_series')},
            },
        ),
    ]
