# Generated by Django 2.2.17 on 2021-04-10 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0013_oldeventsync'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='show_nb',
        ),
        migrations.AlterField(
            model_name='event',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
