# Generated by Django 2.1.8 on 2019-05-11 18:45
from django.db import migrations


def create_spheres(apps, schema_editor):
    Sphere = apps.get_model('calendar', 'Sphere')

    if not Sphere.objects.filter(default=True).exists():
        Sphere.objects.get_or_create(
            name="Everywhere",
            slug="",
            default=True,
        )
    Sphere.objects.get_or_create(
        name="Copenhagen",
        slug="cph",
        default=False,
    )
    Sphere.objects.get_or_create(
        name="Aarhus",
        slug="aah",
        default=False,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0015_autofield_sphere_admins'),
    ]

    operations = [
        migrations.RunPython(create_spheres),
    ]
