# Generated by Django 3.2 on 2021-04-25 19:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calendar', '0016_spheres_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sphere',
            name='admins',
            field=models.ManyToManyField(limit_choices_to={'is_staff': True}, to=settings.AUTH_USER_MODEL),
        ),
    ]
