# Generated by Django 3.2 on 2021-07-31 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0017_alter_sphere_admins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventinterval',
            name='ends',
        ),
        migrations.RemoveField(
            model_name='eventinterval',
            name='starts',
        ),
        migrations.RemoveField(
            model_name='eventinterval',
            name='weekday',
        ),
        migrations.AddField(
            model_name='eventinterval',
            name='end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End of series'),
        ),
        migrations.AddField(
            model_name='eventinterval',
            name='event_time_anchor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calendar.eventtime'),
        ),
        migrations.AddField(
            model_name='eventtime',
            name='interval',
            field=models.ForeignKey(blank=True, help_text='Belonging to a recurring interval', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='times', to='calendar.eventinterval', verbose_name='interval'),
        ),
    ]
