# Generated by Django 3.2 on 2021-10-27 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_location'),
        ('calendar', '0020_on_delete_cascade_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.ForeignKey(blank=True, help_text='The location (venue) of the event.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events_here', to='users.location'),
        ),
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.CharField(blank=True, help_text='Leave blank to use details from existing venue', max_length=255, null=True, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, help_text="Enter details, which will be displayed on the event's own page.", verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='short_description',
            field=models.TextField(blank=True, help_text='A special short version of the event description, leave blank to auto-generate.', verbose_name='short description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='street',
            field=models.CharField(blank=True, help_text='Leave blank to use details from existing venue', max_length=255, null=True, verbose_name='street'),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue_name',
            field=models.CharField(blank=True, help_text='Leave blank to use details from existing venue', max_length=255, null=True, verbose_name='venue name'),
        ),
        migrations.AlterField(
            model_name='event',
            name='zip_code',
            field=models.CharField(blank=True, help_text='Leave blank to use details from existing venue', max_length=16, null=True, verbose_name='zip code'),
        ),
        migrations.AlterField(
            model_name='eventrecurrence',
            name='event_time_anchor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurrence_anchors', to='calendar.eventtime'),
        ),
    ]
