# Generated by Django 3.2 on 2021-10-30 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0021_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location_tba',
            field=models.BooleanField(default=False, verbose_name='TBA'),
        ),
        migrations.AddField(
            model_name='event',
            name='online',
            field=models.BooleanField(default=False, help_text='Use the Description field to tell users how to join or sign up.', verbose_name='Online event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='event',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='street'),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='venue name'),
        ),
        migrations.AlterField(
            model_name='event',
            name='zip_code',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='zip code'),
        ),
    ]
