# Generated by Django 3.2 on 2021-11-01 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0022_online_tba'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventrecurrence',
            name='end',
            field=models.DateField(blank=True, null=True, verbose_name='End of series'),
        ),
    ]
